defmodule Kazi.CLIApplyRenderTreeTest do
  @moduledoc """
  T72.4 (ADR-0086 decision 4): `kazi apply` renders a scoped goal's
  `AGENTS.md` node into its effective workspace BEFORE harness dispatch --
  the same delivery `kazi plan render --tree` does interactively
  (`Kazi.Plan.Tree.render_goal/3`, wired into
  `Kazi.CLI.run_goal_serial_at/6`). Drives the REAL CLI exec core end to end,
  mirroring `Kazi.SerialWorktreeIndirectionTest`'s stub-harness style: a
  harness stub records what it sees in its OWN cwd (the run's effective
  workspace, normally an ephemeral task worktree) at dispatch time, so the
  test can assert the render already happened by then.

  Also pins that this call site is BEST-EFFORT/non-fatal (unlike `--tree`'s
  hard refusal, see `Kazi.Plan.Tree`'s moduledoc): a scoped goal whose
  scope-root already carries a hand-written `AGENTS.md` still dispatches and
  converges normally, only warning on stderr.
  """
  use ExUnit.Case, async: false

  import ExUnit.CaptureIO

  @moduletag :tmp_dir

  setup do
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(Kazi.Repo)
    Ecto.Adapters.SQL.Sandbox.mode(Kazi.Repo, {:shared, self()})
    :ok
  end

  test "a scoped goal has an AGENTS.md node at its scope root by the time the harness runs",
       %{tmp_dir: tmp_dir} do
    work = git_repo(tmp_dir)
    goal_file = write_goal_file(tmp_dir, work, ["pkg/foo/**"])
    marker = Path.join(tmp_dir, "agents-md-snapshot.txt")

    {out, code} =
      with_io(fn ->
        Kazi.CLI.run(
          ["apply", goal_file, "--workspace", work, "--json"],
          adapter_opts: [command: agents_md_recording_harness(tmp_dir, marker)],
          reobserve_interval_ms: 5,
          await_timeout: 15_000
        )
      end)
      |> then(fn {code, out} -> {out, code} end)

    assert code == 0, out

    snapshot = File.read!(marker)
    assert snapshot =~ "FOUND"
    assert snapshot =~ "GENERATED"
    assert snapshot =~ "serial-worktree-fixture"

    # And, per T50.1/ADR-0065 decision 1, the base checkout is never mutated
    # directly -- the render landed in the (now-removed) task worktree, not
    # in the caller's own repo.
    refute File.exists?(Path.join(work, "pkg/foo/AGENTS.md"))
  end

  test "an unscoped goal is unaffected (no AGENTS.md, no crash, run still converges)", %{
    tmp_dir: tmp_dir
  } do
    work = git_repo(tmp_dir)
    goal_file = write_goal_file(tmp_dir, work, [])
    marker = Path.join(tmp_dir, "agents-md-snapshot.txt")

    {_out, code} =
      with_io(fn ->
        Kazi.CLI.run(
          ["apply", goal_file, "--workspace", work, "--json"],
          adapter_opts: [command: agents_md_recording_harness(tmp_dir, marker)],
          reobserve_interval_ms: 5,
          await_timeout: 15_000
        )
      end)
      |> then(fn {code, out} -> {out, code} end)

    assert code == 0
    assert File.read!(marker) =~ "MISSING"
  end

  test "a hand-written AGENTS.md at the scope root does not block dispatch (best-effort)", %{
    tmp_dir: tmp_dir
  } do
    work = git_repo(tmp_dir)
    goal_file = write_goal_file(tmp_dir, work, ["pkg/foo/**"])

    # COMMITTED into the base repo (not merely left untracked) so the fresh
    # task worktree `git worktree add` cuts off HEAD actually carries it --
    # an untracked file in the base checkout would never appear there at all,
    # which would prove nothing about this call site's own hand-written
    # handling.
    hand_written = Path.join(work, "pkg/foo/AGENTS.md")
    File.mkdir_p!(Path.dirname(hand_written))
    File.write!(hand_written, "# hand-authored, not generated by kazi\n")
    {_, 0} = System.cmd("git", ["add", "-A"], cd: work)

    {_, 0} =
      System.cmd("git", ["commit", "-m", "hand-written AGENTS.md"],
        cd: work,
        stderr_to_stdout: true
      )

    {err, code} =
      with_io(:stderr, fn ->
        Kazi.CLI.run(
          ["apply", goal_file, "--workspace", work, "--json"],
          adapter_opts: [command: passing_harness(tmp_dir)],
          reobserve_interval_ms: 5,
          await_timeout: 15_000
        )
      end)
      |> then(fn {code, out} -> {out, code} end)

    assert code == 0
    assert err =~ "T72.4"
    # The base checkout's hand-written file is untouched -- the render this
    # run attempted was against the (now-removed) task worktree, never here.
    assert File.read!(hand_written) == "# hand-authored, not generated by kazi\n"
  end

  # --- fixtures -------------------------------------------------------------

  defp git_repo(tmp_dir) do
    work = Path.join(tmp_dir, "primary-#{System.unique_integer([:positive])}")
    File.mkdir_p!(work)
    {_, 0} = System.cmd("git", ["init", "--initial-branch=main", work], stderr_to_stdout: true)
    {_, 0} = System.cmd("git", ["config", "user.email", "t@example.com"], cd: work)
    {_, 0} = System.cmd("git", ["config", "user.name", "t"], cd: work)
    {_, 0} = System.cmd("git", ["config", "commit.gpgsign", "false"], cd: work)
    File.write!(Path.join(work, "seed.txt"), "seed\n")
    {_, 0} = System.cmd("git", ["add", "-A"], cd: work)
    {_, 0} = System.cmd("git", ["commit", "-m", "seed"], cd: work, stderr_to_stdout: true)
    work
  end

  defp write_goal_file(tmp_dir, workspace, scope_write_paths) do
    path = Path.join(tmp_dir, "artf-#{System.unique_integer([:positive])}.goal.toml")

    File.write!(path, """
    id = "serial-worktree-fixture"
    name = "serial worktree fixture"

    [scope]
    workspace = #{inspect(workspace)}
    write_paths = #{inspect(scope_write_paths)}

    [budget]
    max_iterations = 3

    [[predicate]]
    id = "code"
    provider = "custom_script"
    verdict = "exit_zero"
    cmd = "sh"
    args = ["-c", "test -f fixed.txt"]
    """)

    path
  end

  # Snapshots `pkg/foo/AGENTS.md` from the harness's own cwd (the run's
  # effective workspace) BEFORE it converges the goal -- proving the render
  # already ran by dispatch time, not merely that it runs EVENTUALLY. The
  # marker path is ALWAYS double-quoted in the generated script: ExUnit's
  # `:tmp_dir` slugifies the test's own description into the path, and an
  # unquoted redirect target breaks (silently, as an unterminated shell
  # quote swallowing the rest of the script) the moment a test name's
  # punctuation lands in that slug.
  defp agents_md_recording_harness(tmp_dir, marker) do
    write_stub(
      tmp_dir,
      "agents-md-recording",
      "if [ -f pkg/foo/AGENTS.md ]; then\n" <>
        "  echo \"FOUND\" > \"#{marker}\"\n" <>
        "  cat pkg/foo/AGENTS.md >> \"#{marker}\"\n" <>
        "else\n" <>
        "  echo \"MISSING\" > \"#{marker}\"\n" <>
        "fi\n" <>
        "echo \"the converged fix\" > fixed.txt\nexit 0"
    )
  end

  defp passing_harness(tmp_dir) do
    write_stub(tmp_dir, "passing", "echo \"the converged fix\" > fixed.txt\nexit 0")
  end

  defp write_stub(tmp_dir, name, body) do
    path = Path.join(tmp_dir, "stub-#{name}.sh")
    File.write!(path, "#!/bin/sh\n#{body}\n")
    File.chmod!(path, 0o755)
    path
  end
end
