defmodule Kazi.Workspace.Orientation do
  @moduledoc """
  Write a workspace orientation file before each stateless dispatch (T4.4, UC-022,
  ADR-0010): materialise the `Kazi.Context` orientation pack as an on-disk note in
  the *target* workspace so an agent that reads project files (rather than the
  injected prompt prefix) still starts oriented to where the failing work lives.

  This is the file-on-disk twin of T4.3's prompt-prefix injection. Same map-memory
  source (`Kazi.Context.orientation_pack/3` + `render/1`), two delivery channels:
  the prompt prefix the harness always sees, and this file a harness's own
  project-context scan can pick up. Map memory only — structure, never the
  transcript (ADR-0010 keeps conversation memory out by construction).

  ## Where it is written, and what it never clobbers

  The note is written to `.kazi/context.md` — a kazi-owned path — so it never
  overwrites a user-authored `CLAUDE.md` or any other project file. The whole file
  is kazi-managed: it carries a leading "generated by kazi, do not edit" banner and
  is rewritten wholesale each refresh. A target's own `CLAUDE.md`, if present, is
  left untouched.

  ## Determinism and idempotence ("regenerated on change")

  Content is a pure function of the orientation pack (`Kazi.Context.render/1` is
  byte-stable for equal inputs). `refresh/3`:

    * reads the existing file (if any),
    * renders the current orientation note, and
    * writes **only when the bytes differ** — a no-op when the workspace/graph and
      failing set are unchanged, a rewrite when the underlying structure moves.

  So the file tracks the source: identical inputs leave it byte-identical
  (`:unchanged`), a changed blast radius rewrites it (`:updated`).

  Hermetic: the orientation pack's graph/repo-map seam is injected via
  `context_opts[:graph_source]`, so tests drive both paths with no network and no
  live MCP call (ADR-0010 acceptance).
  """

  alias Kazi.Context

  @rel_path ".kazi/context.md"

  # Banner so a human (or another tool) reading the target workspace knows this
  # file is kazi-managed and regenerated each dispatch — do not hand-edit.
  @banner "<!-- generated by kazi (T4.4, ADR-0010) — do not edit; regenerated each dispatch -->"

  @typedoc "What `refresh/3` did to the orientation file."
  @type outcome :: :created | :updated | :unchanged

  @typedoc "The failing slice, as `Kazi.Context.orientation_pack/3` expects it."
  @type failing :: Context.failing()

  @doc """
  The workspace-relative path of the orientation file kazi writes (`.kazi/context.md`).
  """
  @spec rel_path() :: String.t()
  def rel_path, do: @rel_path

  @doc """
  Refresh the orientation file in `workspace` from the `failing` predicates.

  Builds the orientation pack (`Kazi.Context.orientation_pack/3`), renders it to a
  kazi-managed note, and writes `#{@rel_path}` **only when its bytes change** —
  returning `:created`, `:updated`, or `:unchanged`. Idempotent: re-running with
  the same inputs leaves the file byte-identical and reports `:unchanged`.

  `context_opts` are forwarded to `Kazi.Context.orientation_pack/3` (notably
  `:graph_source` for a hermetic test seam and `:token_budget`).

  Never touches a user-authored `CLAUDE.md`: the note is confined to the kazi-owned
  `.kazi/context.md` path.

  Returns `{:ok, outcome}` or `{:error, reason}` if the file could not be written.
  """
  @spec refresh(String.t(), failing(), keyword()) :: {:ok, outcome()} | {:error, term()}
  def refresh(workspace, failing, context_opts \\ [])
      when is_binary(workspace) and is_list(failing) and is_list(context_opts) do
    path = Path.join(workspace, @rel_path)

    pack = Context.orientation_pack(failing, workspace, context_opts)
    content = render_note(pack)

    case read_existing(path) do
      {:ok, ^content} ->
        {:ok, :unchanged}

      {:ok, _stale} ->
        with :ok <- write(path, content), do: {:ok, :updated}

      :absent ->
        with :ok <- write(path, content), do: {:ok, :created}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # The on-disk note: banner + the deterministic orientation render. A pure
  # function of the pack so equal inputs produce byte-identical files (the
  # idempotence "regenerated on change" requires).
  @spec render_note(Context.Pack.t()) :: String.t()
  defp render_note(pack) do
    @banner <> "\n\n" <> Context.render(pack) <> "\n"
  end

  @spec read_existing(String.t()) :: {:ok, binary()} | :absent | {:error, term()}
  defp read_existing(path) do
    case File.read(path) do
      {:ok, contents} -> {:ok, contents}
      {:error, :enoent} -> :absent
      {:error, reason} -> {:error, {:orientation_read_failed, path, reason}}
    end
  end

  @spec write(String.t(), binary()) :: :ok | {:error, term()}
  defp write(path, content) do
    with :ok <- File.mkdir_p(Path.dirname(path)) do
      case File.write(path, content) do
        :ok -> :ok
        {:error, reason} -> {:error, {:orientation_write_failed, path, reason}}
      end
    end
  end
end
