defmodule Kazi.Loop.WorkspacePrepTest do
  @moduledoc """
  Wiring test for T4.5/T4.4 (ADR-0010 §3): the loop runs `Kazi.Workspace.prepare/2`
  against the target workspace BEFORE it dispatches the harness, exposing the
  code-review-graph MCP in `.mcp.json`, refreshing the graph via the injected
  `:graph_cmd` seam, and writing the `.kazi/context.md` orientation file from the
  iteration's failing predicates. Fully hermetic — a recording harness double, a
  stub graph command, and an injected orientation graph source; no real `claude`
  or `code-review-graph`.
  """
  use ExUnit.Case, async: true

  @moduletag :tmp_dir

  alias Kazi.{Goal, Predicate}

  # A provider that reports a code predicate failing once (so the loop dispatches
  # the agent), then passing (so the loop converges and stops). One status per
  # observation.
  defmodule OnceFailingProvider do
    @behaviour Kazi.PredicateProvider

    @impl true
    def evaluate(_predicate, %{iteration: 0}), do: Kazi.PredicateResult.fail(%{output: "red"})
    def evaluate(_predicate, _context), do: Kazi.PredicateResult.pass()
  end

  # A harness double that, when dispatched, records that it ran and asserts the
  # workspace was already prepared (the .mcp.json exists by the time we run).
  defmodule RecordingHarness do
    @behaviour Kazi.HarnessAdapter

    @impl true
    def run(_prompt, workspace, opts) do
      mcp_present? = File.exists?(Path.join(workspace, ".mcp.json"))
      orientation_present? = File.exists?(Path.join(workspace, ".kazi/context.md"))
      send(Keyword.fetch!(opts, :collector), {:dispatched, mcp_present?, orientation_present?})
      {:ok, %{output: "ok", exit: 0}}
    end
  end

  defmodule NoopIntegrate do
    @behaviour Kazi.Action
    @impl true
    def execute(_action, _context), do: {:ok, %{}}
  end

  defmodule NoopDeploy do
    @behaviour Kazi.Action
    @impl true
    def execute(_action, _context), do: {:ok, %{}}
  end

  test "loop prepares the workspace (mcp + graph freshness) before dispatching", %{tmp_dir: dir} do
    # Seed a fake graph so the freshness step engages and exercises the seam.
    db_dir = Path.join(dir, ".code-review-graph")
    File.mkdir_p!(db_dir)
    File.write!(Path.join(db_dir, "graph.db"), "")

    # A source file so the orientation step's repo-map fallback (the graph CLI has
    # no real binary here and degrades) has real structure to map.
    File.mkdir_p!(Path.join(dir, "lib"))

    File.write!(
      Path.join(dir, "lib/widget.ex"),
      "defmodule Widget do\n  def build, do: :ok\nend\n"
    )

    {:ok, graph_log} = Agent.start_link(fn -> [] end)

    graph_cmd = fn args, _opts ->
      Agent.update(graph_log, &(&1 ++ [args]))
      {"clean\n", 0}
    end

    goal =
      Goal.new("loop-prep-test", predicates: [Predicate.new(:code, :tests)])

    {:ok, loop} =
      Kazi.Loop.start_link(
        goal: goal,
        providers: %{tests: OnceFailingProvider},
        harness: RecordingHarness,
        integrate: NoopIntegrate,
        deploy: NoopDeploy,
        workspace: dir,
        adapter_opts: [collector: self()],
        workspace_opts: [graph_cmd: graph_cmd],
        reobserve_interval_ms: 5,
        flake_max_retries: 0,
        stuck_iterations: 0
      )

    on_exit(fn -> if Process.alive?(loop), do: Kazi.Loop.stop(loop) end)

    # The dispatch ran and saw the workspace already prepared (.mcp.json AND the
    # orientation file both present by dispatch time).
    # Isolation (T59.5, #1025/#1186): a generous deadline, not the old tight 1s.
    # The dispatch genuinely arrives after real workspace-prep IO (graph refresh +
    # orientation write); under full-suite load on a busy box that work is simply
    # slower to schedule, so a tight bound reddens a run that WOULD pass. A larger
    # bound (still well under ExUnit's 60s per-test timeout, so a true hang still
    # fails) waits it out. NOT a Process.sleep -- the message drives the wait.
    assert_receive {:dispatched, true, true}, 15_000

    # The .mcp.json carries the graph MCP server.
    config = dir |> Path.join(".mcp.json") |> File.read!() |> Jason.decode!()
    assert config["mcpServers"]["code-review-graph"]["command"] == "code-review-graph"

    # The injected graph seam ran detect-changes for freshness (no real binary).
    calls = Agent.get(graph_log, & &1)
    assert ["detect-changes", "--brief"] in calls

    # T4.4: the orientation file was written, deriving the failing-predicate set
    # from the loop's own vector (the loop builds the {id, result} slice itself).
    orientation = dir |> Path.join(".kazi/context.md") |> File.read!()
    assert orientation =~ "generated by kazi"
    assert orientation =~ "# Orientation"
  end
end
