defmodule Kazi.Workspace.OrientationTest do
  @moduledoc """
  Hermetic tests for the T4.4 workspace orientation file (ADR-0010, UC-022):
  `.kazi/context.md` is written from the orientation pack, regenerated only when
  the underlying structure changes (idempotent no-op otherwise), and never touches
  a user-authored `CLAUDE.md`. The orientation pack's graph seam is injected via
  `Kazi.Context.StaticGraphSource`, so no real graph / network is required (Tier 2:
  file-I/O boundary over a tmp dir).
  """
  use ExUnit.Case, async: true

  @moduletag :tmp_dir

  alias Kazi.Context.StaticGraphSource
  alias Kazi.PredicateResult
  alias Kazi.Workspace.Orientation

  defp failing(evidence_output) do
    [{:unit, PredicateResult.fail(%{output: evidence_output})}]
  end

  defp source(files) do
    [graph_source: StaticGraphSource.new(origin: :graph, files: files)]
  end

  defp orientation_path(dir), do: Path.join(dir, Orientation.rel_path())

  describe "refresh/3 — creating the orientation file" do
    test "writes .kazi/context.md with up-to-date orientation content", %{tmp_dir: dir} do
      assert {:ok, :created} =
               Orientation.refresh(dir, failing("boom in lib/foo.ex"), source(["lib/foo.ex"]))

      content = File.read!(orientation_path(dir))
      assert content =~ "generated by kazi"
      assert content =~ "# Orientation"
      assert content =~ "lib/foo.ex"
    end

    test "content matches the deterministic Context render for the same inputs", %{tmp_dir: dir} do
      f = failing("error at lib/target.ex")
      opts = source(["lib/target.ex", "lib/other.ex"])

      assert {:ok, :created} = Orientation.refresh(dir, f, opts)

      pack = Kazi.Context.orientation_pack(f, dir, opts)
      assert File.read!(orientation_path(dir)) =~ Kazi.Context.render(pack)
    end
  end

  describe "refresh/3 — idempotence and regeneration on change" do
    test "is a no-op when the inputs are unchanged", %{tmp_dir: dir} do
      f = failing("x")
      opts = source(["lib/a.ex"])

      assert {:ok, :created} = Orientation.refresh(dir, f, opts)
      before = File.read!(orientation_path(dir))
      mtime = File.stat!(orientation_path(dir)).mtime

      assert {:ok, :unchanged} = Orientation.refresh(dir, f, opts)
      assert File.read!(orientation_path(dir)) == before
      # No rewrite: the file was not touched.
      assert File.stat!(orientation_path(dir)).mtime == mtime
    end

    test "regenerates when the underlying structure changes", %{tmp_dir: dir} do
      f = failing("x")

      assert {:ok, :created} = Orientation.refresh(dir, f, source(["lib/a.ex"]))
      first = File.read!(orientation_path(dir))

      # The graph survey now surfaces a different file — the blast radius moved.
      assert {:ok, :updated} = Orientation.refresh(dir, f, source(["lib/b.ex"]))
      second = File.read!(orientation_path(dir))

      refute second == first
      assert second =~ "lib/b.ex"
    end
  end

  describe "refresh/3 — never clobbers a user CLAUDE.md" do
    test "leaves an existing target CLAUDE.md untouched", %{tmp_dir: dir} do
      user_claude = Path.join(dir, "CLAUDE.md")
      File.write!(user_claude, "# my project rules\n")

      assert {:ok, :created} =
               Orientation.refresh(dir, failing("boom"), source(["lib/foo.ex"]))

      # The user's CLAUDE.md is byte-for-byte preserved; kazi wrote elsewhere.
      assert File.read!(user_claude) == "# my project rules\n"
      assert File.exists?(orientation_path(dir))
    end
  end
end
