defmodule Kazi.Reconcile.GherkinImporterBackcompatTest do
  # T41.1 (ADR-0054): the tag-reading extension must be BYTE-IDENTICAL for every
  # existing ADR-0050 behavior spec — backward-compat is a hard requirement, not
  # an aspiration.
  #
  # The proof is a GOLDEN SNAPSHOT of the importer's output for every `.feature`
  # file in the repo, generated by the PRE-T41.1 importer and committed BEFORE
  # the tag-parsing change landed (see the commit that adds
  # `test/fixtures/reconcile/golden/`). The implementation commit leaves these
  # goldens untouched, so `git log -p` on the golden files is the reviewable
  # evidence that untagged (and unrecognized-tag) output did not move a byte.
  #
  # Re-blessing is deliberate and explicit: `KAZI_GOLDEN=overwrite mix test`
  # rewrites the snapshots. Never do that to make a red test green — a diff here
  # means backward-compat broke.
  use ExUnit.Case, async: true

  alias Kazi.Reconcile.GherkinImporter

  @repo_root Path.expand("../../..", __DIR__)
  @golden_dir Path.join(@repo_root, "test/fixtures/reconcile/golden")

  # EVERY `.feature` file in the repo — the literal "every existing ADR-0050
  # behavior spec" the acceptance criterion names. `checkout.feature` also
  # carries real Cucumber tags (`@checkout`, `@smoke`) that are NOT in kazi's
  # vocabulary, so it doubles as the unrecognized-tags-are-ignored regression.
  @specs [
    {"checkout", "test/fixtures/reconcile/checkout.feature"},
    {"example", "docs/specs/example.feature"}
  ]

  for {name, path} <- @specs do
    test "#{path} imports byte-identically to the pre-T41.1 importer" do
      text = File.read!(Path.join(@repo_root, unquote(path)))
      {:ok, map} = GherkinImporter.import_map(text)

      actual = canonical(map)
      golden_path = Path.join(@golden_dir, unquote(name) <> ".import.golden")

      if System.get_env("KAZI_GOLDEN") == "overwrite" do
        File.mkdir_p!(@golden_dir)
        File.write!(golden_path, actual)
      end

      assert File.exists?(golden_path),
             "missing golden #{golden_path} — generate it with KAZI_GOLDEN=overwrite mix test"

      assert actual == File.read!(golden_path),
             "#{unquote(path)} no longer imports byte-identically to the pre-T41.1 " <>
               "importer. Tags are ADDITIVE (ADR-0054): an untagged Scenario — and a " <>
               "Scenario carrying only tags outside kazi's vocabulary — must derive " <>
               "exactly the predicate it derived before. Do NOT re-bless the golden to " <>
               "make this pass."
    end
  end

  # A stable, order-independent rendering of the goal map: maps become sorted
  # key/value lists so the snapshot pins CONTENT, not the BEAM's map iteration
  # order (which is not part of the importer's contract). Lists keep their order
  # — predicate document order and sorted group order ARE the contract.
  defp canonical(term) do
    term
    |> sorted()
    |> inspect(limit: :infinity, printable_limit: :infinity, pretty: true, width: 80)
  end

  defp sorted(%{} = map) when not is_struct(map) do
    map
    |> Enum.map(fn {k, v} -> {to_string(k), sorted(v)} end)
    |> Enum.sort_by(fn {k, _v} -> k end)
  end

  defp sorted(list) when is_list(list), do: Enum.map(list, &sorted/1)
  defp sorted(other), do: other
end
