defmodule Kazi.Goal.Roadmap.Render do
  @moduledoc """
  Renders a roadmap (T45.1) as a human-readable, GENERATED markdown plan
  document (T45.5, UC-059): the goal DAG as a wave-sectioned WBS with a
  read-model-driven checkbox per goal, progress counts, and a prominent
  "GENERATED — DO NOT HAND-EDIT" banner.

  The waves are the roadmap's topological `needs` frontiers — the SAME
  computation `kazi apply <roadmap> --explain` prints (`Kazi.Goal.Roadmap.frontiers/1`,
  which delegates to `Kazi.Fleet.frontiers/1`), so the rendered document can never
  disagree with the schedule the executor runs.

  `render/2` is PURE: it takes the loaded roadmap and a `verdicts` map
  (`goal-id => :converged | :pending | :unknown`) and returns markdown. The CLI
  builds the verdict map from the read-model (a converged goal's latest iteration),
  so a re-render after a verdict changes reflects the new state deterministically —
  there is no cache, the document is a projection of live state every time.

  The document is GENERATED. Hand-edits to a written file (`--out <path>`) are
  overwritten on the next render; the banner says so loudly, so an operator edits
  the roadmap-file (the source of truth), never the rendered view.
  """

  alias Kazi.Goal
  alias Kazi.Goal.Roadmap

  @typedoc "A goal's convergence verdict read back from the read-model."
  @type verdict :: :converged | :pending | :unknown

  @banner_headline "GENERATED — DO NOT HAND-EDIT"

  @doc "The banner headline, exposed so tests/callers can assert its presence."
  @spec banner_headline() :: String.t()
  def banner_headline, do: @banner_headline

  @doc """
  Renders `roadmap` to a deterministic markdown plan. `verdicts` maps each goal id
  to its convergence verdict (`:converged` renders `[x]`, anything else `[ ]`); an
  id absent from the map is treated as `:unknown`.
  """
  @spec render(Roadmap.t(), %{optional(String.t()) => verdict()}) :: String.t()
  def render(%Roadmap{} = roadmap, verdicts \\ %{}) when is_map(verdicts) do
    frontiers = Roadmap.frontiers(roadmap)
    nodes_by_id = Map.new(roadmap.nodes, &{&1.id, &1})

    [
      banner(),
      header(roadmap),
      progress(roadmap.nodes, verdicts),
      waves(frontiers, nodes_by_id, verdicts)
    ]
    |> Enum.join("\n")
    |> ensure_trailing_newline()
  end

  # --- sections ---

  defp banner do
    """
    <!-- #{@banner_headline} -->
    <!-- This file is generated by `kazi plan render`. Edits are LOST on the next -->
    <!-- render. Change the roadmap-file (the source of truth) and re-render. -->

    > **#{@banner_headline}.** Generated by `kazi plan render` from the read-model.
    > Any manual edit to this file is overwritten on the next render — edit the
    > roadmap-file and re-run `kazi plan render` instead.
    """
  end

  defp header(%Roadmap{path: path}) do
    "# Roadmap: #{source_name(path)}\n"
  end

  defp source_name(nil), do: "(unnamed)"
  defp source_name(path), do: Path.basename(path)

  defp progress(nodes, verdicts) do
    total = length(nodes)
    converged = Enum.count(nodes, &(verdict_for(&1.id, verdicts) == :converged))
    percent = if total == 0, do: 0, else: round(converged * 100 / total)

    "**Progress:** #{converged} / #{total} goals converged (#{percent}%)\n"
  end

  defp waves([], _nodes_by_id, _verdicts), do: "_No goals in this roadmap._\n"

  defp waves(frontiers, nodes_by_id, verdicts) do
    frontiers
    |> Enum.with_index(1)
    |> Enum.map_join("\n", fn {ids, wave_index} ->
      wave_section(ids, wave_index, nodes_by_id, verdicts)
    end)
  end

  defp wave_section(ids, wave_index, nodes_by_id, verdicts) do
    items =
      Enum.map_join(ids, "\n", fn id ->
        node = Map.fetch!(nodes_by_id, id)
        goal_item(node, verdicts)
      end)

    "## Wave #{wave_index}\n\n#{items}\n"
  end

  defp goal_item(%Roadmap.Node{} = node, verdicts) do
    verdict = verdict_for(node.id, verdicts)

    "- #{checkbox(verdict)} `#{node.id}`#{goal_title(node.goal)} — #{status_label(verdict)}#{needs_suffix(node.needs)}"
  end

  defp checkbox(:converged), do: "[x]"
  defp checkbox(_), do: "[ ]"

  defp status_label(:converged), do: "converged"
  defp status_label(:pending), do: "pending"
  defp status_label(:unknown), do: "unknown"

  defp goal_title(%Goal{name: name}) when is_binary(name) and name != "", do: " — #{name}"
  defp goal_title(_goal), do: ""

  defp needs_suffix([]), do: ""

  defp needs_suffix(needs) do
    " (needs: #{needs |> Enum.map_join(", ", &"`#{&1}`")})"
  end

  defp verdict_for(id, verdicts), do: Map.get(verdicts, id, :unknown)

  defp ensure_trailing_newline(string) do
    if String.ends_with?(string, "\n"), do: string, else: string <> "\n"
  end
end
